### ISSUE TITLE
Custom metrics

### ISSUE THREAD

**Issue by luissimas** [MATRIXXSoftware/xk6-diameter#13]
Hello!

From my understanding, currently the extension provides no custom metrics. When I execute a test I get the following output:

![image](https://github.com/MATRIXXSoftware/xk6-diameter/assets/41878330/1549ba61-1a77-4023-afe7-b5a1be3d128c)

I'd like to be able to gather metrics around the latency of requests and the number of requests made during the test. The final goal is to be able to extract information about the latency's p(90), p(95), p(99) and the RPS. Is this on the roadmap of the project? If not, would it be possible to implement such feature?

I'll look into the K6 metrics API and start experimenting with it, but I'd love to hear your thoughts on this.

**Comment by luissimas** [comment]
I was able to hack something together that looks like this:

![image](https://github.com/MATRIXXSoftware/xk6-diameter/assets/41878330/aa4d511d-3114-4cf6-bd44-a1456c662643)

I'll probably open a draft PR so we can better discuss the implementation. I think a good addition to that would be to add a metric similar to HTTP's `http_req_failed` with the option for the user to define how to determine if a request was successful or not, probably an API like HTTP's [setResponseCallback](https://k6.io/docs/javascript-api/k6-http/setresponsecallback/).

**Comment by lwlee2608** [comment]
Implemented in #14
