### ISSUE TITLE
Inquiry about Adding CCR for AVPs with Multiple Flags

### ISSUE THREAD

**Issue by itsMohammadHeidari** [MATRIXXSoftware/xk6-diameter#15]
Hello MATRIXXSoftware team,

I hope this message finds you well. Firstly, thank you for your ongoing work on this project.

I have a query regarding the usage of the 'ccr.add()' method. Specifically, I'm interested in adding a Credit Control Request (CCR) for Attribute-Value Pairs (AVPs) that **must have more than one flag**. For instance, the `AoC-Request-Type` AVP with code 2055 requires both Vendor-Specific (V) and Mandatory (M) flags.

Could you please confirm if it is possible to use the existing 'ccr.add()' method to achieve this? If yes, could you provide some guidance or examples on how to appropriately utilize it for AVPs with multiple flags?

_Thank you for your time and assistance._

![2flags](https://github.com/MATRIXXSoftware/xk6-diameter/assets/83077336/a7f3dcae-502b-4719-88db-5db72c1252cc)

**Comment by lwlee2608** [comment]
If you specify a VendorId, the V flag will automatically be set to true.
```js
ccr.add(avp.New(2055, 10415, flag.M, data.Enumerated(0)))
```

If you also need the P flag to be true, you can do it like this:
```js
ccr.add(avp.New(2055, 10415, flag.M|flag.P,  data.Enumerated(0)))
```

**Comment by itsMohammadHeidari** [comment]
Thanks a bunch, @lwlee2608! 🙌
