### ISSUE TITLE
SCTP support

### ISSUE THREAD

**Issue by luissimas** [MATRIXXSoftware/xk6-diameter#7]
Hello! 

First of all thanks for the work on this extension. I'm currently entering a load test phase for a Diameter application and I this tool was as a great surprise in the K6 ecossystem. 

From my understanding [go-diameter](https://github.com/fiorix/go-diameter/tree/v4.0.4) supports the SCTP protocol, but I couldn't find any config options for the transport-layer protocol for this extension. Is there currently any way to configure the transport-layer protocol? If not, is there any plan to add this feature?

**Comment by lwlee2608** [comment]
I'm glad to hear that the extension is helpful for your testing. Thank you for your PR and contribution.
